# 베이스 이미지 설정 (OpenJDK 17)
FROM openjdk:17-slim

# 작업 디렉토리 설정
WORKDIR /app

# 호스트의 JAR 파일을 컨테이너로 복사
COPY build/libs/* /app/Community.jar

# 환경 변수 설정 (환경 변수로 설정된 민감한 정보 처리)
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
ENV JWT_SECRET=${JWT_SECRET}
ENV SERVER_SSL_KEY_STORE=${SERVER_SSL_KEY_STORE}
ENV SERVER_SSL_KEY_STORE_PASSWORD=${SERVER_SSL_KEY_STORE_PASSWORD}
ENV SERVER_SSL_KEY_STORE_TYPE=${SERVER_SSL_KEY_STORE_TYPE}
ENV SERVER_SSL_KEY_ALIAS=${SERVER_SSL_KEY_ALIAS}

# 컨테이너 시작 시 실행될 명령어
ENTRYPOINT ["java", "-jar", "/app/your-application.jar"]