databaseChangeLog:
  - changeSet:
      id: 1
      author: y1412
      changes:
        - createTable:
            tableName: app_config
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: config_key
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: config_value
                  type: VARCHAR(255)
